### PR TITLE
adds an `ls` command to agents

### PR DESCRIPTION
**Pull request by audibleblink**
### Pull Request (PR) Checklist
- [x] I have read the [CONTRIBUTING](../CONTRIBUTING.MD) doc
- [x] PR is from **a topic/feature/bugfix branch** off the **dev branch** (right side)
- [x] PR is against the **dev branch** (left side)
- [x] Merlin compiles without errors
- [x] Passes linting checks and unit tests
- [x] Updated [CHANGELOG](../CHANGELOG.MD)
- [ ] Updated README documentation (if applicable)

### Change Type
- [x] Addition
- [ ] Bugfix
- [ ] Modification
- [ ] Removal
- [ ] Security

### Description

In order to stay off the commandline, some basic filesystem navigation and IO should be done by the agent in a way that doesn't rely on the native shell.

This initial PR adds an `ls` command.

### CODE REVIEW

**Comment by Ne0nd0g** [comment]
Tested agent on Ubuntu 18 and Windows 10. Basic functionality worked good.

The command does not handle file paths with a space. Needs to be updated to handle file paths with a space.

**Comment by Ne0nd0g** [comment]
How do you feel about changing the message type to something like `native`, `internal`, or `inherent`?

**Comment by capnspacehook** [comment]
Something like `NativeCmd` made sense to me as well

**Comment by audibleblink** [comment]
Addressed! Thanks for the feedback

**Pull request merged**
