### PR TITLE
Add Killdate to Agents

### PR DESCRIPTION
**Pull request by ahhh**
### Pull Request (PR) Checklist
- [X] I have read the [CONTRIBUTING](../CONTRIBUTING.MD) doc
- [X] PR is from **a topic/feature/bugfix branch** off the **dev branch** (right side)
- [X] PR is against the **dev branch** (left side)
- [X] Merlin compiles without errors
- [X] Passes linting checks and unit tests
- [X] Updated [CHANGELOG](../CHANGELOG.MD)
- [X] Updated README documentation (if applicable)

### Change Type
- [X] Addition
- [ ] Bugfix
- [ ] Modification
- [ ] Removal
- [ ] Security

### Description
- Adding a kill date to stop execution of agents after a certain date. If the killdate is 0 (the default) it is ignored. Otherwise if the killdate is before the current date, the agent will not execute. This is for when an agent is in long term persistence and you don't want to infect a target past the lifecycle of the operation. Tested this on macos and windows.

### CODE REVIEW

**Comment by ahhh** [comment]
I'm not sure if I can update the wiki page for agents, but it would be nice to add a note on how to use the killdate there

**Comment by Ne0nd0g** [comment]
If you will the content to this thread, I'll transfer it to the Wiki. I'm also not sure if you could just make PR against the wiki or not. Seems like it would be something Github would support.

**Comment by Ne0nd0g** [comment]
You can ignore the AppVeyor build failure. I'm working on migrating to a new Linux worker that isn't setup correctly.

**Comment by Ne0nd0g** [comment]
Please make sure to submit PRs from a feature branch off of dev and not from master.

> PR is from **a topic/feature/bugfix branch** off the **dev branch** (right side)

**Comment by Ne0nd0g** [comment]
I want to add in a method to set the kill date from the server using an `AgentControl` message. Are there any negative consequence from doing so that you wanted to avoid? If not, I'll add it in.

**Comment by ahhh** [comment]
We should emphasis the distinction in the wiki that hardcoding the killdate value is useful for terminating the agent when it's been persisted, vs using the `AgentControl` message from the server which is useful for telling an active agent when to stop running

**Comment by Ne0nd0g** [comment]
Just updated the wiki, let me know what you think.

**Pull request merged**
