### PR TITLE
Begin to define agent tests

### PR DESCRIPTION
**Pull request by C-Sto**
### Pull Request (PR) Checklist
- [x] I have read the [CONTRIBUTING](../CONTRIBUTING.MD) doc
- [x] PR is from **a topic/feature/bugfix branch** off the **dev branch** (right side)
- [x] PR is against the **dev branch** (left side)
- [x] Merlin compiles without errors
- [x] Passes linting checks and unit tests
- [ ] Updated [CHANGELOG](../CHANGELOG.MD)
- [ ] Updated README documentation (if applicable)

### Change Type
- [x] Addition
- [ ] Bugfix
- [ ] Modification
- [ ] Removal
- [ ] Security

### Description

Added the start of some test cases for agents

### CODE REVIEW

**Comment by Ne0nd0g** [comment]
Please make sure to submit PRs from a feature branch off of dev and not from your master. I'll see if I can use this PR as is though.

> PR is from **a topic/feature/bugfix branch** off the **dev branch** (right side)

**Comment by Ne0nd0g** [comment]
I'm looking it to standards and best practice to see if the `pkg/agent/testServer` directory and package are needed. Honestly, I'm not that familiar with tests in go. Initial searching seems to indicate the test should be self contained or maybe in the `/test` directory off the project root.

**Comment by Ne0nd0g** [comment]
Have we considered using go's [httptest](https://golang.org/pkg/net/http/httptest/) package?

**Comment by C-Sto** [comment]
Tests that check exposed functions can be outside the package - it's not possible to test functions like `initialcheckin` in isolation without being inside the package. API level tests can go into a test dir, but I think given the agents expose so little, most of the testing will be done internally. Go's cookiejar tests  are a similar setup to what I was going for with the server/client thing if you'd like a canon example: [https://golang.org/src/net/http/cookiejar/](https://golang.org/src/net/http/cookiejar/)

I haven't looked into the httptest package, but it seems like a good idea.

**Pull request merged**
